AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda Functions for Order Management System

Parameters:
  LambdaExecutionRoleArn:
    Type: String
    Description: IAM Role ARN (LabRole)

  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String

  LambdaSecurityGroup:
    Type: String

  RdsEndpoint:
    Type: String
  DbName:
    Type: String
  DbUsername:
    Type: String
  DbPassword:
    Type: String

  OrdersBucketName:
    Type: String

  StepFunctionArn:
    Type: String
    Default: ""
    Description: (Optional) Step Function ARN for order processing workflow

Resources:

  DependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: lks-layer-dependencies
      Description: Shared dependencies for Order Management system
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: your-layer-bucket
        S3Key: layers/dependencies.zip

  ### 1. Order Management ###
  OrderManagementLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-order-management
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref DependenciesLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          DB_ENDPOINT: !Ref RdsEndpoint
          DB_NAME: !Ref DbName
          DB_USERNAME: !Ref DbUsername
          DB_PASSWORD: !Ref DbPassword
          ORDERS_BUCKET: !Ref OrdersBucketName
          STEP_FUNCTION_ARN: !Ref StepFunctionArn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"message": "Order Management Lambda"}

  ### 2. Process Payment ###
  ProcessPaymentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-process-payment
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 30
      Layers:
        - !Ref DependenciesLayer
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"message": "Process Payment Lambda"}

  ### 3. Update Inventory ###
  UpdateInventoryLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-update-inventory
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Handler: app.lambda_handler
      MemorySize: 256
      Timeout: 15
      Layers:
        - !Ref DependenciesLayer
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"message": "Update Inventory Lambda"}

  ### 4. Send Notification ###
  SendNotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-send-notification
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Handler: app.lambda_handler
      MemorySize: 256
      Timeout: 10
      Layers:
        - !Ref DependenciesLayer
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"message": "Send Notification Lambda"}

  ### 5. Generate Report ###
  GenerateReportLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-generate-report
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Handler: app.lambda_handler
      MemorySize: 1024
      Timeout: 60
      Layers:
        - !Ref DependenciesLayer
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"message": "Generate Report Lambda"}

  ### 6. Init Database ###
  InitDatabaseLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lks-lambda-init-db
      Runtime: python3.12
      Role: !Ref LambdaExecutionRoleArn
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 300
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          DB_ENDPOINT: !Ref RdsEndpoint
          DB_NAME: !Ref DbName
          DB_USERNAME: !Ref DbUsername
          DB_PASSWORD: !Ref DbPassword
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"message": "Init Database Lambda"}

Outputs:
  OrderManagementLambdaArn:
    Value: !GetAtt OrderManagementLambda.Arn
