AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Buckets for Order Documents and Application Logs

Parameters:
  YourName:
    Type: String
    Description: Your name (lowercase, no spaces)

Resources:

  OrderDocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lks-orders-${YourName}-2026"
      VersioningConfiguration:
        Status: Enabled

      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

      LifecycleConfiguration:
        Rules:
          - Id: OrderDocumentsLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: INTELLIGENT_TIERING
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365

      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - "*"
            MaxAge: 3000

  OrderDocumentsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OrderDocumentsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPublicAccess
            Effect: Allow
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::lks-orders-${YourName}-2026"
              - !Sub "arn:aws:s3:::lks-orders-${YourName}-2026/*"

  ApplicationLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lks-logs-${YourName}-2026"
      LifecycleConfiguration:
        Rules:
          - Id: LogsLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: INTELLIGENT_TIERING
            ExpirationInDays: 90

Outputs:
  OrderDocumentsBucketName:
    Value: !Ref OrderDocumentsBucket

  ApplicationLogsBucketName:
    Value: !Ref ApplicationLogsBucket
